### ISSUE TITLE
i.MX6ULL-NPI Image problem

### ISSUE THREAD

**Issue by versamodule** [Seeed-Studio/image-builder#2]
Using the current i.MX6ULL-NPI image. after performing an apt-get update. then the apt-get upgrade it fails with:
Err:9 https://wildfireteam.gitee.io buster/main armhf fire-config armhf 0.1.12
  404  Not Found [IP: 212.64.62.174 443]
E: Failed to fetch https://wildfireteam.gitee.io/pool/main/e/embedfire/fire-config_0.1.12_armhf.deb  404  Not Found [IP: 212.64.62.174 443]

Also why am i seeing this in the boot process. 
[    1.531387] fec 20b4000.ethernet: Invalid MAC address: 00:00:00:00:00:00

**Comment by Hansen0314** [comment]
thanks for your feedback. we have been updating this newest image that does not exist 404 error.
